site_name: Matthew Goldsberry
site_description: Computer Science Student
site_author: Matthew Goldsberry
site_url: https://MatthewGoldsberry.github.io/

nav:
  - About: index.md
  - Projects:
    - Projects Overview: projects/projects.md
    - CubeCats: projects/cube-cats.md
    - Smart Pong: projects/smart-pong.md
  - Experience & Skills: experience.md
  - Resume: resume.md

theme:
  name: zensical
  language: en
  custom_dir: overrides

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
  - assets/styles/extra.css

